import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { PassThrough } from "node:stream";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import type { GqlTransport } from "../src/github/client.js";
import type { JobDeps, JobManagerApi, JobResult } from "../src/jobs/manager.js";
import type { JobStatus } from "../src/jobs/registry.js";
import type { ModelProvider } from "../src/model/provider.js";
import type { MineConfig } from "../src/schemas/mine-config.js";
import { ProvenanceSchema, type ContestedItem, type Provenance, type RuleRecord } from "../src/schemas/provenance.js";

// vi.mock with a hoisted factory that wraps (not replaces) the real emitDraft, per
// this repo's "use vi.mock with hoisted factories for ESM modules, not vi.spyOn on
// ESM exports" convention. Wrapping (rather than a bare vi.fn stub) means the
// happy-path test drives a REAL emitDraft — proving the CLI's write gate produces
// actually-written files, not just a call-count assertion — while still letting
// other tests assert call counts and override behavior with mockRejectedValueOnce.
vi.mock("../src/emitter/emit.js", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../src/emitter/emit.js")>();
  return { ...actual, emitDraft: vi.fn(actual.emitDraft) };
});

const { runMineCli } = await import("../src/cli.js");
const { emitDraft, EmitRefusedError } = await import("../src/emitter/emit.js");

const tmpRepo = () => mkdtemp(join(tmpdir(), "prlore-cli-"));

beforeEach(() => {
  vi.mocked(emitDraft).mockClear();
});

// ---- fixtures (mirrors test/server-tools.test.ts's local fixture builders) -------

function mkRule(overrides: Partial<RuleRecord> = {}): RuleRecord {
  return {
    id: "1",
    statement: "Always write tests first",
    category: "testing",
    polarity: "prescriptive",
    scope: [],
    score: 0.9,
    verdict: "corroborated",
    evidence: [],
    exemplars: [],
    lastCorroborated: "2026-06-01T00:00:00Z",
    ...overrides,
  };
}

function mkContested(overrides: Partial<ContestedItem> = {}): ContestedItem {
  return {
    id: "c1",
    statement: "Use tabs, not spaces",
    reason: "conflicting guidance",
    sides: [],
    ...overrides,
  };
}

function mkProvenance(rules: RuleRecord[], contested: ContestedItem[] = []): Provenance {
  return ProvenanceSchema.parse({
    generatedAt: "2026-07-01T00:00:00Z",
    intent: "help contributors",
    rules,
    dropped: [],
    contested,
  });
}

function mkDraft(contested: ContestedItem[]): string {
  const lines = ["<!-- generated by prlore -->", "# Conventions", "", "auto-generated", "", "## Testing", "- **Always write tests first**", ""];
  if (contested.length > 0) {
    lines.push("## Needs your call (contested)");
    for (const item of contested) lines.push(`- ${item.statement} — ${item.reason}`);
  }
  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}

const stubTransport: GqlTransport = async <T>(): Promise<T> => {
  throw new Error("stub transport should never be called");
};
const stubProvider: ModelProvider = {
  spentUsd: () => 0,
  async complete() {
    throw new Error("stub provider should never be called");
  },
};

async function makeDeps(_config: MineConfig, ctx: { repoPath: string; stateDir: string }): Promise<JobDeps> {
  return { transport: stubTransport, provider: stubProvider, stateDir: ctx.stateDir, repoPath: ctx.repoPath };
}

// A scripted JobManagerApi: status() walks a fixed sequence of statuses (holding on
// the last entry once exhausted), so runMineCli's poll loop can be driven
// deterministically — no real 5s sleeps in tests. Paired with CliDeps.pollIntervalMs:
// 0 (this test suite's chosen seam for making the poll loop testable — see report),
// which collapses the loop's inter-poll delay so a multi-poll script still resolves
// instantly.
class ScriptedJobManager implements JobManagerApi {
  startCalls: { config: MineConfig; deps: JobDeps }[] = [];
  private idx = 0;
  constructor(private readonly statuses: JobStatus[], private readonly res: JobResult | null = null) {}

  start(config: MineConfig, deps: JobDeps): { jobId: string; resumed: boolean } {
    this.startCalls.push({ config, deps });
    return { jobId: "job-1", resumed: false };
  }
  status(): JobStatus {
    const s = this.statuses[Math.min(this.idx, this.statuses.length - 1)]!;
    this.idx++;
    return s;
  }
  async cancel(): Promise<{ checkpointed: boolean }> {
    return { checkpointed: false };
  }
  result(): JobResult | null {
    return this.res;
  }
}

function readyStatus(overrides: Partial<JobStatus> = {}): JobStatus {
  return { state: "ready-for-preview", jobId: "job-1", stage: "ready-for-preview", counters: {}, warnings: [], tokensSpentUsd: 0.42, ...overrides };
}

function streams() {
  const stdout = new PassThrough();
  const stderr = new PassThrough();
  const outChunks: string[] = [];
  const errChunks: string[] = [];
  stdout.on("data", (c) => outChunks.push(String(c)));
  stderr.on("data", (c) => errChunks.push(String(c)));
  return { stdout, stderr, out: () => outChunks.join(""), err: () => errChunks.join("") };
}

function baseArgv(repo: string, repoPath: string, extra: string[] = []): string[] {
  return [repo, "--intent", "test intent", "--repo-path", repoPath, ...extra];
}

// ---- --author -----------------------------------------------------------------

test("--author repeated twice -> both land in config.authors", async () => {
  const repoPath = await tmpRepo();
  const manager = new ScriptedJobManager([readyStatus()], { draft: mkDraft([]), provenance: mkProvenance([mkRule()]), contested: [] });
  const { stdout, stderr } = streams();

  const code = await runMineCli(
    ["octo/repo", "--intent", "test intent", "--repo-path", repoPath, "--author", "alice", "--author", "bob"],
    { makeDeps, manager, stdout, stderr, confirm: async () => true, pollIntervalMs: 0 },
  );

  expect(code).toBe(0);
  expect(manager.startCalls).toHaveLength(1);
  expect(manager.startCalls[0]!.config.authors).toEqual(["alice", "bob"]);
});

test("--author without --intent switches the default intent to the lessons-learned phrasing", async () => {
  const repoPath = await tmpRepo();
  const manager = new ScriptedJobManager([readyStatus()], { draft: mkDraft([]), provenance: mkProvenance([mkRule()]), contested: [] });
  const { stdout, stderr } = streams();

  const code = await runMineCli(["octo/repo", "--repo-path", repoPath, "--author", "alice"], {
    makeDeps,
    manager,
    stdout,
    stderr,
    confirm: async () => true,
    pollIntervalMs: 0,
  });

  expect(code).toBe(0);
  expect(manager.startCalls).toHaveLength(1);
  expect(manager.startCalls[0]!.config.intent).toMatch(/lessons|standing lessons/i);
  expect(manager.startCalls[0]!.config.intent).toMatch(/review feedback/i);
});

test("--author WITH an explicit --intent -> the explicit intent wins", async () => {
  const repoPath = await tmpRepo();
  const manager = new ScriptedJobManager([readyStatus()], { draft: mkDraft([]), provenance: mkProvenance([mkRule()]), contested: [] });
  const { stdout, stderr } = streams();

  const code = await runMineCli(
    ["octo/repo", "--repo-path", repoPath, "--author", "alice", "--intent", "my custom intent"],
    { makeDeps, manager, stdout, stderr, confirm: async () => true, pollIntervalMs: 0 },
  );

  expect(code).toBe(0);
  expect(manager.startCalls[0]!.config.intent).toBe("my custom intent");
});

test("no --author -> the existing default intent is unchanged", async () => {
  const repoPath = await tmpRepo();
  const manager = new ScriptedJobManager([readyStatus()], { draft: mkDraft([]), provenance: mkProvenance([mkRule()]), contested: [] });
  const { stdout, stderr } = streams();

  const code = await runMineCli(["octo/repo", "--repo-path", repoPath], {
    makeDeps,
    manager,
    stdout,
    stderr,
    confirm: async () => true,
    pollIntervalMs: 0,
  });

  expect(code).toBe(0);
  expect(manager.startCalls[0]!.config.intent).toBe(
    "onboard an AI coding agent to contribute changes matching this repo's conventions",
  );
  expect(manager.startCalls[0]!.config.authors).toEqual([]);
});

// ---- arg parsing table ------------------------------------------------------------

test("missing positional owner/repo -> usage printed to stderr, exit 2", async () => {
  const { stdout, stderr, err } = streams();
  const code = await runMineCli([], {
    makeDeps,
    manager: new ScriptedJobManager([readyStatus()]),
    stdout,
    stderr,
    confirm: async () => true,
    pollIntervalMs: 0,
  });
  expect(code).toBe(2);
  expect(err()).toMatch(/usage/i);
});

test("unknown flag -> usage printed to stderr, exit 2", async () => {
  const { stdout, stderr, err } = streams();
  const code = await runMineCli(["octo/repo", "--bogus-flag", "x"], {
    makeDeps,
    manager: new ScriptedJobManager([readyStatus()]),
    stdout,
    stderr,
    confirm: async () => true,
    pollIntervalMs: 0,
  });
  expect(code).toBe(2);
  expect(err()).toMatch(/usage/i);
});

test("--since and --days together -> mutual exclusion error, exit 2", async () => {
  const { stdout, stderr, err } = streams();
  const code = await runMineCli(
    ["octo/repo", "--intent", "x", "--since", "2026-01-01T00:00:00Z", "--days", "30"],
    { makeDeps, manager: new ScriptedJobManager([readyStatus()]), stdout, stderr, confirm: async () => true, pollIntervalMs: 0 },
  );
  expect(code).toBe(2);
  expect(err()).toMatch(/--since/);
  expect(err()).toMatch(/--days/);
});

test("--days converts to an ISO --since via the injected now(), threaded into the started config", async () => {
  const { stdout, stderr } = streams();
  const manager = new ScriptedJobManager([readyStatus()], { draft: mkDraft([]), provenance: mkProvenance([mkRule()]), contested: [] });
  const fixedNow = () => Date.parse("2026-07-10T00:00:00.000Z");
  const repoPath = await tmpRepo();
  const code = await runMineCli(baseArgv("octo/repo", repoPath, ["--days", "10"]), {
    makeDeps,
    manager,
    stdout,
    stderr,
    confirm: async () => true,
    pollIntervalMs: 0,
    now: fixedNow,
  });
  expect(code).toBe(0);
  expect(manager.startCalls).toHaveLength(1);
  expect(manager.startCalls[0]!.config.timeRange.since).toBe("2026-06-30T00:00:00.000Z");
});

test("invalid config (malformed repo) fails MineConfigSchema.parse -> human-readable zod error, exit 2", async () => {
  const { stdout, stderr, err } = streams();
  const code = await runMineCli(["not-a-valid-repo-format", "--intent", "x"], {
    makeDeps,
    manager: new ScriptedJobManager([readyStatus()]),
    stdout,
    stderr,
    confirm: async () => true,
    pollIntervalMs: 0,
  });
  expect(code).toBe(2);
  expect(err()).toMatch(/repo/i);
  expect(err()).not.toMatch(/\bZodError\b/); // human-readable, not a raw error dump
});

test("--budget with a non-numeric value -> usage error, exit 2", async () => {
  const { stdout, stderr, err } = streams();
  const code = await runMineCli(["octo/repo", "--intent", "x", "--budget", "not-a-number"], {
    makeDeps,
    manager: new ScriptedJobManager([readyStatus()]),
    stdout,
    stderr,
    confirm: async () => true,
    pollIntervalMs: 0,
  });
  expect(code).toBe(2);
  expect(err()).toMatch(/--budget/);
});

// ---- --max-rules (v0.3 Task 4) ------------------------------------------------

test("--max-rules threads a positive integer into config.output.maxRules", async () => {
  const repoPath = await tmpRepo();
  const manager = new ScriptedJobManager([readyStatus()], { draft: mkDraft([]), provenance: mkProvenance([mkRule()]), contested: [] });
  const { stdout, stderr } = streams();

  const code = await runMineCli(baseArgv("octo/repo", repoPath, ["--max-rules", "5"]), {
    makeDeps,
    manager,
    stdout,
    stderr,
    confirm: async () => true,
    pollIntervalMs: 0,
  });

  expect(code).toBe(0);
  expect(manager.startCalls[0]!.config.output.maxRules).toBe(5);
});

test("no --max-rules -> config.output.maxRules falls through to the schema default (60)", async () => {
  const repoPath = await tmpRepo();
  const manager = new ScriptedJobManager([readyStatus()], { draft: mkDraft([]), provenance: mkProvenance([mkRule()]), contested: [] });
  const { stdout, stderr } = streams();

  const code = await runMineCli(baseArgv("octo/repo", repoPath), {
    makeDeps,
    manager,
    stdout,
    stderr,
    confirm: async () => true,
    pollIntervalMs: 0,
  });

  expect(code).toBe(0);
  expect(manager.startCalls[0]!.config.output.maxRules).toBe(60);
});

test("--max-rules 0 -> usage error, exit 2 (positive int only, no zero-means-uncapped)", async () => {
  const { stdout, stderr, err } = streams();
  const code = await runMineCli(["octo/repo", "--intent", "x", "--max-rules", "0"], {
    makeDeps,
    manager: new ScriptedJobManager([readyStatus()]),
    stdout,
    stderr,
    confirm: async () => true,
    pollIntervalMs: 0,
  });
  expect(code).toBe(2);
  expect(err()).toMatch(/--max-rules/);
});

test("--max-rules with a non-integer value -> usage error, exit 2", async () => {
  const { stdout, stderr, err } = streams();
  const code = await runMineCli(["octo/repo", "--intent", "x", "--max-rules", "3.5"], {
    makeDeps,
    manager: new ScriptedJobManager([readyStatus()]),
    stdout,
    stderr,
    confirm: async () => true,
    pollIntervalMs: 0,
  });
  expect(code).toBe(2);
  expect(err()).toMatch(/--max-rules/);
});

test("--max-rules with a negative value -> usage error, exit 2", async () => {
  const { stdout, stderr, err } = streams();
  const code = await runMineCli(["octo/repo", "--intent", "x", "--max-rules", "-1"], {
    makeDeps,
    manager: new ScriptedJobManager([readyStatus()]),
    stdout,
    stderr,
    confirm: async () => true,
    pollIntervalMs: 0,
  });
  expect(code).toBe(2);
  expect(err()).toMatch(/--max-rules/);
});

// ---- happy flow: preview, confirm=true, write ---------------------------------

test("happy flow: polls to ready, prints preview, writes after confirm=true, exit 0", async () => {
  const repoPath = await tmpRepo();
  const rule = mkRule();
  const provenance = mkProvenance([rule]);
  const draft = mkDraft([]);
  const manager = new ScriptedJobManager(
    [
      { state: "running", jobId: "job-1", stage: "fetching", counters: { prsFetched: 1 }, warnings: [], tokensSpentUsd: 0.1 },
      readyStatus({ tokensSpentUsd: 0.5 }),
    ],
    { draft, provenance, contested: [] },
  );
  const { stdout, stderr, out, err } = streams();
  const confirm = vi.fn(async () => true);

  const code = await runMineCli(baseArgv("octo/repo", repoPath), {
    makeDeps,
    manager,
    stdout,
    stderr,
    confirm,
    pollIntervalMs: 0,
  });

  expect(code).toBe(0);
  expect(confirm).toHaveBeenCalledTimes(1);
  expect(confirm.mock.calls[0]![0]).toMatch(/write/i);
  expect(confirm.mock.calls[0]![0]).toMatch(/AGENTS\.md/);

  // preview printed to stdout before the write
  expect(out()).toContain("Always write tests first");

  // emitDraft was actually called (real, unmocked implementation) and wrote the file
  expect(emitDraft).toHaveBeenCalledTimes(1);
  const written = await readFile(join(repoPath, "AGENTS.md"), "utf8");
  expect(written).toContain("Always write tests first");

  // "wrote:" status line went to stderr, not stdout (stdout is draft-only for piping)
  expect(err()).toMatch(/wrote.*AGENTS\.md/);
  expect(err()).toContain(join(repoPath, "AGENTS.md"));
  expect(out()).not.toMatch(/wrote/i);

  // stdout contains draft content, no trailing status lines
  expect(out()).toContain("Always write tests first");
  expect(out()).not.toMatch(/wrote|not written|dry.run/i);

  // progress line(s) went to stderr
  expect(err()).toMatch(/fetching/);
});

test("direct-mode confirm prompt names the target file only (no root AGENTS.md → direct mode)", async () => {
  const repoPath = await tmpRepo();
  const manager = new ScriptedJobManager([readyStatus()], { draft: mkDraft([]), provenance: mkProvenance([mkRule()]), contested: [] });
  const { stdout, stderr } = streams();
  const confirm = vi.fn(async () => true);

  const code = await runMineCli(baseArgv("octo/repo", repoPath), {
    makeDeps,
    manager,
    stdout,
    stderr,
    confirm,
    pollIntervalMs: 0,
  });

  expect(code).toBe(0);
  const question = confirm.mock.calls[0]![0];
  expect(question).toBe("Write AGENTS.md?");
});

test("pointer-mode confirm prompt names .prlore/AGENTS.md and the appended pointer block", async () => {
  const repoPath = await tmpRepo();
  // An existing unmarked human AGENTS.md → pointer mode: the prompt must say the
  // full doc goes to .prlore/AGENTS.md and only a pointer block is added to the
  // human file, not the misleading direct-mode "Write AGENTS.md?".
  await writeFile(join(repoPath, "AGENTS.md"), "# Hand-authored\n\nsome prose\n", "utf8");
  const manager = new ScriptedJobManager([readyStatus()], { draft: mkDraft([]), provenance: mkProvenance([mkRule()]), contested: [] });
  const { stdout, stderr } = streams();
  const confirm = vi.fn(async () => true);

  const code = await runMineCli(baseArgv("octo/repo", repoPath), {
    makeDeps,
    manager,
    stdout,
    stderr,
    confirm,
    pollIntervalMs: 0,
  });

  expect(code).toBe(0);
  const question = confirm.mock.calls[0]![0];
  expect(question).toMatch(/\.prlore\/AGENTS\.md/);
  expect(question).toMatch(/pointer block/i);
  expect(question).toMatch(/^Write /);

  // And the write actually adopted pointer mode: full doc under .prlore/, human
  // prose preserved above the appended pointer block.
  const humanFile = await readFile(join(repoPath, "AGENTS.md"), "utf8");
  expect(humanFile.startsWith("# Hand-authored\n\nsome prose\n")).toBe(true);
  expect(humanFile).toContain(".prlore/AGENTS.md");
  const prloreDoc = await readFile(join(repoPath, ".prlore", "AGENTS.md"), "utf8");
  expect(prloreDoc).toContain("Always write tests first");
});

test("confirm=false -> emitDraft is never called, exit 0, output says not written", async () => {
  const repoPath = await tmpRepo();
  const manager = new ScriptedJobManager([readyStatus()], { draft: mkDraft([]), provenance: mkProvenance([mkRule()]), contested: [] });
  const { stdout, stderr, out, err } = streams();
  const confirm = vi.fn(async () => false);

  const code = await runMineCli(baseArgv("octo/repo", repoPath), {
    makeDeps,
    manager,
    stdout,
    stderr,
    confirm,
    pollIntervalMs: 0,
  });

  expect(code).toBe(0);
  expect(confirm).toHaveBeenCalledTimes(1);
  expect(emitDraft).not.toHaveBeenCalled();
  // "not written" status goes to stderr, stdout is draft-only
  expect(err()).toMatch(/not written/i);
  expect(out()).not.toMatch(/not written/i);
  // stdout contains draft content, no status lines
  expect(out()).toContain("Always write tests first");
});

test("--dry-run never calls emitDraft even with --yes, exit 0", async () => {
  const repoPath = await tmpRepo();
  const manager = new ScriptedJobManager([readyStatus()], { draft: mkDraft([]), provenance: mkProvenance([mkRule()]), contested: [] });
  const { stdout, stderr, out, err } = streams();
  const confirm = vi.fn(async () => true);

  const code = await runMineCli(baseArgv("octo/repo", repoPath, ["--dry-run", "--yes"]), {
    makeDeps,
    manager,
    stdout,
    stderr,
    confirm,
    pollIntervalMs: 0,
  });

  expect(code).toBe(0);
  expect(confirm).not.toHaveBeenCalled(); // --dry-run short-circuits before the confirm gate
  expect(emitDraft).not.toHaveBeenCalled();
  // "dry run: not written" status goes to stderr, stdout is draft-only
  expect(err()).toMatch(/dry.run/i);
  expect(out()).not.toMatch(/dry.run/i);
  // stdout contains draft content, no status lines
  expect(out()).toContain("Always write tests first");
});

test("--yes skips the confirm prompt and writes directly", async () => {
  const repoPath = await tmpRepo();
  const manager = new ScriptedJobManager([readyStatus()], { draft: mkDraft([]), provenance: mkProvenance([mkRule()]), contested: [] });
  const { stdout, stderr, out } = streams();
  const confirm = vi.fn(async () => true);

  const code = await runMineCli(baseArgv("octo/repo", repoPath, ["--yes"]), {
    makeDeps,
    manager,
    stdout,
    stderr,
    confirm,
    pollIntervalMs: 0,
  });

  expect(code).toBe(0);
  expect(confirm).not.toHaveBeenCalled();
  expect(emitDraft).toHaveBeenCalledTimes(1);
  const written = await readFile(join(repoPath, "AGENTS.md"), "utf8");
  expect(written).toContain("Always write tests first");
});

// ---- failed job -----------------------------------------------------------------

test("failed job -> error text printed to stderr, exit 1, no write attempted", async () => {
  const repoPath = await tmpRepo();
  const manager = new ScriptedJobManager([{ state: "failed", jobId: "job-1", error: "model budget exhausted: $9.00 of $9.00 cap" }]);
  const { stdout, stderr, err } = streams();

  const code = await runMineCli(baseArgv("octo/repo", repoPath, ["--yes"]), {
    makeDeps,
    manager,
    stdout,
    stderr,
    confirm: async () => true,
    pollIntervalMs: 0,
  });

  expect(code).toBe(1);
  expect(err()).toMatch(/budget exhausted/);
  expect(emitDraft).not.toHaveBeenCalled();
});

// ---- EmitRefusedError -------------------------------------------------------------

test("EmitRefusedError from the write gate -> its message printed, exit 1", async () => {
  const repoPath = await tmpRepo();
  const manager = new ScriptedJobManager([readyStatus()], { draft: mkDraft([]), provenance: mkProvenance([mkRule()]), contested: [] });
  const { stdout, stderr, err } = streams();
  vi.mocked(emitDraft).mockRejectedValueOnce(new EmitRefusedError(join(repoPath, "AGENTS.md"), "missing prlore:begin/end marker pair"));

  const code = await runMineCli(baseArgv("octo/repo", repoPath, ["--yes"]), {
    makeDeps,
    manager,
    stdout,
    stderr,
    confirm: async () => true,
    pollIntervalMs: 0,
  });

  expect(code).toBe(1);
  expect(err()).toMatch(/refusing to write/);
  expect(err()).toMatch(/marker/);
});

// ---- contested items: listed to stderr, stripped from the written file, via the ---
// ---- SAME hardened finalize function the MCP write tool uses ----------------------

test("contested items are listed to stderr and stripped from the written file using the shared hardened finalize path", async () => {
  const repoPath = await tmpRepo();

  // Poisoned fixture mirroring test/server-tools.test.ts's hardened-path test: a
  // contested item whose OWN statement embeds the literal contested-header text,
  // placed AFTER the genuine header in the rendered draft. A naive lastIndexOf (or
  // a reimplementation that doesn't share render.ts's line-anchored regex) would
  // find the poisoned occurrence instead of the genuine one and strip too little,
  // leaving the header and contested bullets in the written file.
  const normalContested = mkContested({ id: "c1", statement: "Use tabs, not spaces", reason: "conflicting guidance" });
  const poisonContested = mkContested({
    id: "c2",
    statement: "Mentions ## Needs your call (contested) inline as prose",
    reason: "poisoned reason",
  });
  const contested = [normalContested, poisonContested];
  const draft = [
    "<!-- generated by prlore -->",
    "# Conventions",
    "",
    "## Testing",
    "- **Always write tests first**",
    "",
    "## Needs your call (contested)",
    `- ${normalContested.statement} — ${normalContested.reason}`,
    `- ${poisonContested.statement} — ${poisonContested.reason}`,
  ].join("\n") + "\n";

  const manager = new ScriptedJobManager([readyStatus()], {
    draft,
    provenance: mkProvenance([mkRule()], contested),
    contested,
  });
  const { stdout, stderr, err } = streams();

  const code = await runMineCli(baseArgv("octo/repo", repoPath, ["--yes"]), {
    makeDeps,
    manager,
    stdout,
    stderr,
    confirm: async () => true,
    pollIntervalMs: 0,
  });

  expect(code).toBe(0);

  // Both contested items surfaced on stderr with the remediation hint.
  expect(err()).toContain("Use tabs, not spaces");
  expect(err()).toContain("Mentions ## Needs your call (contested) inline as prose");
  expect(err()).toMatch(/left out of the written file/i);
  expect(err()).toMatch(/write tool|edit manually/i);

  // Neither contested item, nor the header itself, survived into the written file —
  // this is the hardened, line-anchored strip (proves the CLI shares the exact
  // finalizeDraft render.ts's guard makes safe, not a reimplementation).
  const written = await readFile(join(repoPath, "AGENTS.md"), "utf8");
  expect(written).not.toContain("Needs your call (contested)");
  expect(written).not.toContain("Use tabs, not spaces");
  expect(written).not.toContain("Mentions ## Needs your call");
  expect(written).toContain("Always write tests first");
});
