import { mkdtemp, readFile, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { afterEach, beforeEach, expect, test } from "vitest";
import { buildServer } from "../src/server.js";
import type { JobDeps, JobManagerApi, JobResult } from "../src/jobs/manager.js";
import type { JobStatus } from "../src/jobs/registry.js";
import type { MineConfig } from "../src/schemas/mine-config.js";
import { ProvenanceSchema, type ContestedItem, type Provenance, type RuleRecord } from "../src/schemas/provenance.js";

// mine() calls resolveToken() with the real process.env by default; set GITHUB_TOKEN
// so it short-circuits without shelling out to `gh auth token` (no network/process
// spawn in tests, per Global Constraints).
const ORIGINAL_TOKEN = process.env.GITHUB_TOKEN;
beforeEach(() => {
  process.env.GITHUB_TOKEN = "gho_test_fake";
});
afterEach(() => {
  if (ORIGINAL_TOKEN === undefined) delete process.env.GITHUB_TOKEN;
  else process.env.GITHUB_TOKEN = ORIGINAL_TOKEN;
});

// ---- a fully-controllable stub JobManagerApi -------------------------------

class StubJobManager implements JobManagerApi {
  private st: JobStatus = { state: "idle" };
  private res: JobResult | null = null;
  startCalls: { config: MineConfig; deps: JobDeps }[] = [];
  cancelCalls: string[] = [];
  private jobCounter = 0;

  start(config: MineConfig, deps: JobDeps): { jobId: string; resumed: boolean } {
    this.startCalls.push({ config, deps });
    const jobId = `job-${++this.jobCounter}`;
    this.st = { state: "running", jobId, stage: "fetching", counters: {}, warnings: [], tokensSpentUsd: 0 };
    this.res = null;
    return { jobId, resumed: false };
  }

  status(jobId?: string): JobStatus {
    if (jobId !== undefined && jobId !== this.st.jobId) return { state: "idle" };
    return this.st;
  }

  async cancel(jobId: string): Promise<{ checkpointed: boolean }> {
    this.cancelCalls.push(jobId);
    if (this.st.jobId !== jobId) return { checkpointed: false };
    this.st = { ...this.st, state: "cancelled" };
    return { checkpointed: true };
  }

  result(jobId: string): JobResult | null {
    if (this.st.jobId !== jobId || this.st.state !== "ready-for-preview") return null;
    return this.res;
  }

  /** Test-only: simulates the pipeline reaching ready-for-preview. */
  completeToReady(result: JobResult): void {
    this.res = result;
    this.st = { ...this.st, state: "ready-for-preview", stage: "ready-for-preview" };
  }
}

function mkRule(overrides: Partial<RuleRecord> = {}): RuleRecord {
  return {
    id: "1",
    statement: "Always write tests first",
    category: "testing",
    polarity: "prescriptive",
    scope: [],
    score: 0.9,
    verdict: "corroborated",
    evidence: [],
    exemplars: [],
    lastCorroborated: "2026-06-01T00:00:00Z",
    ...overrides,
  };
}

function mkContested(overrides: Partial<ContestedItem> = {}): ContestedItem {
  return {
    id: "c1",
    statement: "Use tabs, not spaces",
    reason: "conflicting guidance",
    sides: [],
    ...overrides,
  };
}

function mkProvenance(rules: RuleRecord[], contested: ContestedItem[] = []): Provenance {
  return ProvenanceSchema.parse({
    generatedAt: "2026-07-01T00:00:00Z",
    intent: "help contributors",
    rules,
    dropped: [],
    contested,
  });
}

function mkDraft(contested: ContestedItem[]): string {
  const lines = ["<!-- generated by prlore -->", "# Conventions", "", "auto-generated", "", "## Testing", "- **Always write tests first**", ""];
  if (contested.length > 0) {
    lines.push("## Needs your call (contested)");
    for (const item of contested) lines.push(`- ${item.statement} — ${item.reason}`);
  }
  return lines.join("\n").replace(/\n+$/, "") + "\n";
}

async function connectedClient(manager?: JobManagerApi) {
  const server = manager ? buildServer(manager) : buildServer();
  const client = new Client({ name: "test-client", version: "0.0.0" });
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  await Promise.all([server.connect(serverTransport), client.connect(clientTransport)]);
  return client;
}

function textOf(res: { content?: unknown }): string {
  const [first] = res.content as { type: string; text: string }[];
  return first!.text;
}

const tmpRepo = () => mkdtemp(join(tmpdir(), "prlore-server-tools-"));

// ---- Phase 1 compatibility: default construction ---------------------------

test("buildServer() with no args still boots (Phase 1 default-construction contract)", async () => {
  const client = await connectedClient();
  const { tools } = await client.listTools();
  expect(tools.map((t) => t.name)).toEqual(expect.arrayContaining(["mine", "status", "cancel", "preview", "write"]));
});

// ---- happy path: mine -> status -> preview -> write -------------------------

test("mine -> status -> preview -> write happy path", async () => {
  const repoPath = await tmpRepo();
  const manager = new StubJobManager();
  const client = await connectedClient(manager);

  const mineRes = await client.callTool({
    name: "mine",
    arguments: { repo: "octo/repo", intent: "help new contributors", repoPath },
  });
  expect(mineRes.isError).toBeFalsy();
  const { jobId, resumed } = JSON.parse(textOf(mineRes));
  expect(typeof jobId).toBe("string");
  expect(resumed).toBe(false);

  // mine wired the deps as spec'd: a transport function, a provider with spentUsd(),
  // repoPath/stateDir defaulted.
  expect(manager.startCalls).toHaveLength(1);
  const { deps } = manager.startCalls[0]!;
  expect(typeof deps.transport).toBe("function");
  expect(typeof deps.provider.spentUsd).toBe("function");
  expect(deps.repoPath).toBe(repoPath);
  expect(deps.stateDir).toBe(join(repoPath, ".prlore"));

  const statusRes = await client.callTool({ name: "status", arguments: { jobId } });
  const status = JSON.parse(textOf(statusRes));
  expect(status.state).toBe("running");
  expect(status.jobId).toBe(jobId);

  // fake pipeline reaches ready-for-preview
  const rule = mkRule();
  const provenance = mkProvenance([rule]);
  manager.completeToReady({ draft: mkDraft([]), provenance, contested: [] });

  const previewRes = await client.callTool({ name: "preview", arguments: {} });
  expect(previewRes.isError).toBeFalsy();
  const preview = JSON.parse(textOf(previewRes));
  expect(preview.markdown).toContain("Always write tests first");
  expect(preview.stats).toEqual({ rulesIncluded: 1, droppedCount: 0, contestedCount: 0 });
  expect(preview.targetExists).toBe(false);
  expect(preview.wouldRefuse).toBe(false);
  expect(typeof preview.confirmToken).toBe("string");

  const writeRes = await client.callTool({ name: "write", arguments: { confirmToken: preview.confirmToken } });
  expect(writeRes.isError).toBeFalsy();
  const writeOut = JSON.parse(textOf(writeRes));
  expect(writeOut.pathsWritten).toContain(join(repoPath, "AGENTS.md"));

  const written = await readFile(join(repoPath, "AGENTS.md"), "utf8");
  expect(written).toContain("Always write tests first");
});

// ---- write without a preview -------------------------------------------------

test("write without ever calling preview fails with an error, not a crash", async () => {
  const repoPath = await tmpRepo();
  const manager = new StubJobManager();
  const client = await connectedClient(manager);

  await client.callTool({ name: "mine", arguments: { repo: "octo/repo", intent: "x", repoPath } });

  const writeRes = await client.callTool({ name: "write", arguments: { confirmToken: "not-a-real-token" } });
  expect(writeRes.isError).toBe(true);
  expect(textOf(writeRes)).toMatch(/confirm token/i);
  await expect(stat(join(repoPath, "AGENTS.md"))).rejects.toThrow();
});

// ---- stale token: a second preview invalidates the first ---------------------

test("a stale confirmToken from an earlier preview is rejected once a newer preview has run", async () => {
  const repoPath = await tmpRepo();
  const manager = new StubJobManager();
  const client = await connectedClient(manager);

  await client.callTool({ name: "mine", arguments: { repo: "octo/repo", intent: "x", repoPath } });
  manager.completeToReady({ draft: mkDraft([]), provenance: mkProvenance([mkRule()]), contested: [] });

  const firstPreview = JSON.parse(textOf(await client.callTool({ name: "preview", arguments: {} })));
  const secondPreview = JSON.parse(textOf(await client.callTool({ name: "preview", arguments: {} })));
  expect(secondPreview.confirmToken).not.toBe(firstPreview.confirmToken);

  const staleWrite = await client.callTool({
    name: "write",
    arguments: { confirmToken: firstPreview.confirmToken },
  });
  expect(staleWrite.isError).toBe(true);
  expect(textOf(staleWrite)).toMatch(/confirm token/i);

  const freshWrite = await client.callTool({
    name: "write",
    arguments: { confirmToken: secondPreview.confirmToken },
  });
  expect(freshWrite.isError).toBeFalsy();
});

// ---- resolveContested keep/drop -----------------------------------------------

test("resolveContested: kept items are appended as resolved, dropped/unresolved items never appear", async () => {
  const repoPath = await tmpRepo();
  const manager = new StubJobManager();
  const client = await connectedClient(manager);

  await client.callTool({ name: "mine", arguments: { repo: "octo/repo", intent: "x", repoPath } });

  const kept = mkContested({ id: "keep-1", statement: "Prefer tabs" });
  const dropped = mkContested({ id: "drop-1", statement: "Prefer spaces" });
  const unresolved = mkContested({ id: "unresolved-1", statement: "Prefer four-space indents" });
  const contested = [kept, dropped, unresolved];
  manager.completeToReady({ draft: mkDraft(contested), provenance: mkProvenance([mkRule()], contested), contested });

  const preview = JSON.parse(textOf(await client.callTool({ name: "preview", arguments: {} })));
  expect(preview.markdown).toContain("Needs your call (contested)");

  const writeRes = await client.callTool({
    name: "write",
    arguments: {
      confirmToken: preview.confirmToken,
      resolveContested: [
        { id: "keep-1", action: "keep" },
        { id: "drop-1", action: "drop" },
      ],
    },
  });
  expect(writeRes.isError).toBeFalsy();

  const written = await readFile(join(repoPath, "AGENTS.md"), "utf8");
  expect(written).toContain("Prefer tabs");
  expect(written).toContain("_(resolved)_");
  expect(written).not.toContain("Prefer spaces");
  expect(written).not.toContain("Prefer four-space indents");
  expect(written).not.toContain("Needs your call (contested)");
});

// ---- interview prompt ----------------------------------------------------------

test("the interview prompt is listed and fetchable, returning static intake-script text", async () => {
  const manager = new StubJobManager();
  const client = await connectedClient(manager);

  const { prompts } = await client.listPrompts();
  expect(prompts.map((p) => p.name)).toContain("interview");

  const got = await client.getPrompt({ name: "interview" });
  expect(got.messages.length).toBeGreaterThan(0);
  const [first] = got.messages;
  expect(first!.content.type).toBe("text");
  const text = (first!.content as { type: "text"; text: string }).text;
  expect(text).toMatch(/repo/i);
  expect(text).toMatch(/intent/i);
  expect(text).toMatch(/mine/i);
});

// ---- status §8 shape --------------------------------------------------------

test("status returns idle before any job (Phase 1 contract preserved)", async () => {
  const manager = new StubJobManager();
  const client = await connectedClient(manager);
  const res = await client.callTool({ name: "status", arguments: {} });
  expect(JSON.parse(textOf(res))).toEqual({ state: "idle" });
});

test("status shape matches spec §8 keys once a job is running", async () => {
  const repoPath = await tmpRepo();
  const manager = new StubJobManager();
  const client = await connectedClient(manager);

  await client.callTool({ name: "mine", arguments: { repo: "octo/repo", intent: "x", repoPath } });
  const res = await client.callTool({ name: "status", arguments: {} });
  const status = JSON.parse(textOf(res));

  for (const key of ["state", "jobId", "stage", "counters", "warnings", "tokensSpentUsd"]) {
    expect(status).toHaveProperty(key);
  }
});

// ---- mine rejects while running ------------------------------------------------

test("mine surfaces a running-job rejection as a tool error, not a crash", async () => {
  const repoPath = await tmpRepo();
  const manager: JobManagerApi = {
    start() {
      throw new Error("a job is already running on this manager instance");
    },
    status: () => ({ state: "running" }),
    cancel: async () => ({ checkpointed: false }),
    result: () => null,
  };
  const client = await connectedClient(manager);

  const res = await client.callTool({ name: "mine", arguments: { repo: "octo/repo", intent: "x", repoPath } });
  expect(res.isError).toBe(true);
  expect(textOf(res)).toMatch(/already running/i);
});

// ---- preview before ready-for-preview -----------------------------------------

test("preview before the job reaches ready-for-preview is a clean tool error", async () => {
  const repoPath = await tmpRepo();
  const manager = new StubJobManager();
  const client = await connectedClient(manager);

  await client.callTool({ name: "mine", arguments: { repo: "octo/repo", intent: "x", repoPath } });
  const res = await client.callTool({ name: "preview", arguments: {} });
  expect(res.isError).toBe(true);
  expect(textOf(res)).toMatch(/ready.for.preview/i);
});

// ---- cancel ------------------------------------------------------------------

test("cancel returns { checkpointed } and never crashes for an unknown jobId", async () => {
  const manager = new StubJobManager();
  const client = await connectedClient(manager);
  const res = await client.callTool({ name: "cancel", arguments: { jobId: "no-such-job" } });
  expect(res.isError).toBeFalsy();
  expect(JSON.parse(textOf(res))).toEqual({ checkpointed: false });
});
