import type { MineConfig } from "../schemas/mine-config.js";
import type { ContestedItem, RuleRecord } from "../schemas/provenance.js";
import type { DocPlan } from "./select.js";

const MAX_CITATIONS = 3;

function citationsFor(rule: RuleRecord, config: MineConfig): string {
  if (config.output.citations !== "inline-light") return "";
  const prs = [...new Set(rule.evidence.filter((e) => e.verified).map((e) => e.pr))].sort((a, b) => a - b);
  if (prs.length === 0) return "";
  const shown = prs.slice(0, MAX_CITATIONS);
  return ` _(${shown.map((n) => `#${n}`).join(", ")})_`;
}

function renderBullet(rule: RuleRecord, config: MineConfig): string {
  const prefix = rule.verdict === "trending-toward"
    ? `- **[migration in progress]** ${rule.statement}`
    : `- **${rule.statement}**`;
  const rationale = rule.rationale ? ` — ${rule.rationale}` : "";
  const citations = citationsFor(rule, config);
  return `${prefix}${rationale}${citations}`;
}

export function renderDraft(
  plan: DocPlan,
  rules: RuleRecord[],
  contested: ContestedItem[],
  config: MineConfig,
): string {
  const ruleById = new Map(rules.map((r) => [r.id, r]));
  const lines: string[] = [];

  lines.push("<!-- generated by prlore -->");
  lines.push(`# ${plan.title}`);
  lines.push("");
  lines.push(plan.overview);
  lines.push("");

  for (const section of plan.sections) {
    lines.push(`## ${section.heading}`);
    for (const id of section.ruleIds) {
      const rule = ruleById.get(id);
      if (!rule) continue; // enforced plans should never carry unknown ids; defensive only
      lines.push(renderBullet(rule, config));
    }
    lines.push("");
  }

  if (contested.length > 0) {
    lines.push("## Needs your call (contested)");
    for (const item of contested) {
      lines.push(`- ${item.statement} — ${item.reason}`);
    }
  }

  return lines.join("\n");
}
