import type { MineConfig } from "../schemas/mine-config.js";
import type { ContestedItem, RuleRecord } from "../schemas/provenance.js";
import type { DocPlan } from "./select.js";

const MAX_CITATIONS = 3;

// Every interpolated model-derived field goes through this before hitting the
// rendered markdown: a statement/rationale/etc. is untrusted text that could carry
// a newline-smuggled "## Injected heading" or an HTML comment that closes/reopens
// a structural marker like "<!-- prlore:end -->". Collapsing whitespace runs to a
// single space keeps everything on one line (no new heading, no list-item break),
// and stripping comment delimiters keeps a model-authored string from masquerading
// as a document-structure comment. Marker stripping runs to a FIXPOINT: a single
// pass is bypassable — "<<!--!-- prlore:end ---->>" reassembles to
// "<!-- prlore:end -->" once the inner markers are removed — so keep stripping
// until the string stops changing.
function sanitize(s: string): string {
  let out = s.replace(/\s+/g, " ");
  let prev: string;
  do {
    prev = out;
    out = out.replaceAll("<!--", "").replaceAll("-->", "");
  } while (out !== prev);
  return out.trim();
}

function citationsFor(rule: RuleRecord, config: MineConfig): string {
  if (config.output.citations !== "inline-light") return "";
  const prs = [...new Set(rule.evidence.filter((e) => e.verified).map((e) => e.pr))].sort((a, b) => a - b);
  if (prs.length === 0) return "";
  const shown = prs.slice(0, MAX_CITATIONS);
  return ` _(${shown.map((n) => `#${n}`).join(", ")})_`;
}

function renderBullet(rule: RuleRecord, config: MineConfig): string {
  const statement = sanitize(rule.statement);
  const prefix = rule.verdict === "trending-toward"
    ? `- **[migration in progress]** ${statement}`
    : rule.verdict === "trending-away"
      ? `- **[fading]** ${statement}` // survived scoring but is on its way out — must not read as settled
      : `- **${statement}**`;
  const rationale = rule.rationale ? ` — ${sanitize(rule.rationale)}` : "";
  const citations = citationsFor(rule, config);
  return `${prefix}${rationale}${citations}`;
}

export function renderDraft(
  plan: DocPlan,
  rules: RuleRecord[],
  contested: ContestedItem[],
  config: MineConfig,
): string {
  const ruleById = new Map(rules.map((r) => [r.id, r]));
  const lines: string[] = [];

  lines.push("<!-- generated by prlore -->");
  lines.push(`# ${sanitize(plan.title)}`);
  lines.push("");
  lines.push(sanitize(plan.overview));
  lines.push("");

  for (const section of plan.sections) {
    lines.push(`## ${sanitize(section.heading)}`);
    for (const id of section.ruleIds) {
      const rule = ruleById.get(id);
      if (!rule) continue; // enforced plans should never carry unknown ids; defensive only
      lines.push(renderBullet(rule, config));
    }
    lines.push("");
  }

  if (contested.length > 0) {
    lines.push("## Needs your call (contested)");
    for (const item of contested) {
      lines.push(`- ${sanitize(item.statement)} — ${sanitize(item.reason)}`);
    }
  }

  // Normalize EOF to exactly one trailing newline, regardless of how the last
  // section/contested-block left the lines array.
  return lines.join("\n").replace(/\n+$/, "") + "\n";
}
