import type { MineConfig } from "../schemas/mine-config.js";
import type { ContestedItem, RuleRecord } from "../schemas/provenance.js";
import type { DocPlan } from "./select.js";

const MAX_CITATIONS = 3;

// Every interpolated model-derived field goes through this before hitting the
// rendered markdown: a statement/rationale/etc. is untrusted text that could carry
// a newline-smuggled "## Injected heading" or an HTML comment that closes/reopens
// a structural marker like "<!-- prlore:end -->". Collapsing whitespace runs to a
// single space keeps everything on one line (no new heading, no list-item break),
// and stripping comment delimiters keeps a model-authored string from masquerading
// as a document-structure comment. Marker stripping runs to a FIXPOINT: a single
// pass is bypassable — "<<!--!-- prlore:end ---->>" reassembles to
// "<!-- prlore:end -->" once the inner markers are removed — so keep stripping
// until the string stops changing.
function sanitize(s: string): string {
  let out = s.replace(/\s+/g, " ");
  let prev: string;
  do {
    prev = out;
    out = out.replaceAll("<!--", "").replaceAll("-->", "");
  } while (out !== prev);
  return out.trim();
}

// The literal text of the contested-section header (see the "## Needs your call
// (contested)" push below). Exported so consumers that need to recognize the
// genuine header line (e.g. server-tools.ts's finalizeDraft, which anchors its
// contested-section strip to a full-line match of this text) derive it from the
// same source of truth instead of hardcoding a second copy that could drift.
export const CONTESTED_HEADER = "Needs your call (contested)";

// A DocPlan section heading is model-controlled, untrusted text (see planDoc in
// select.ts — the LLM chooses it, and select.ts's enforce() only validates rule
// ids, not heading content). It's rendered directly as its own "## <heading>"
// line below. If its sanitized form happened to equal CONTESTED_HEADER exactly,
// the rendered document would contain two lines that read identically as
// "## Needs your call (contested)": this poisoned section heading (which always
// renders earlier, since sections come before the contested block) and the
// genuine header. A consumer that locates "the" contested header by the first
// full-line match (finalizeDraft in server-tools.ts) would then anchor to the
// poisoned line and treat everything after it — every later section plus the
// real contested block — as past the cut point, silently dropping it from the
// written file (a fail-closed under-write: preview shows more than gets
// written). This is the single place every section heading renders through, so
// guarding here closes the hole for any caller, present or future. Perturbing
// with a deterministic, human-legible prefix (rather than rejecting the whole
// plan) keeps a plan usable even if a model picks this exact heading text.
function guardSectionHeading(heading: string): string {
  return heading === CONTESTED_HEADER ? `Section: ${heading}` : heading;
}

function citationsFor(rule: RuleRecord, config: MineConfig): string {
  if (config.output.citations !== "inline-light") return "";
  const prs = [...new Set(rule.evidence.filter((e) => e.verified).map((e) => e.pr))].sort((a, b) => a - b);
  if (prs.length === 0) return "";
  const shown = prs.slice(0, MAX_CITATIONS);
  return ` _(${shown.map((n) => `#${n}`).join(", ")})_`;
}

function renderBullet(rule: RuleRecord, config: MineConfig): string {
  const statement = sanitize(rule.statement);
  const prefix = rule.verdict === "trending-toward"
    ? `- **[migration in progress]** ${statement}`
    : rule.verdict === "trending-away"
      ? `- **[fading]** ${statement}` // survived scoring but is on its way out — must not read as settled
      : `- **${statement}**`;
  const rationale = rule.rationale ? ` — ${sanitize(rule.rationale)}` : "";
  const citations = citationsFor(rule, config);
  return `${prefix}${rationale}${citations}`;
}

export function renderDraft(
  plan: DocPlan,
  rules: RuleRecord[],
  contested: ContestedItem[],
  config: MineConfig,
): string {
  const ruleById = new Map(rules.map((r) => [r.id, r]));
  const lines: string[] = [];

  lines.push("<!-- generated by prlore -->");
  lines.push(`# ${sanitize(plan.title)}`);
  lines.push("");
  lines.push(sanitize(plan.overview));
  lines.push("");

  for (const section of plan.sections) {
    lines.push(`## ${guardSectionHeading(sanitize(section.heading))}`);
    for (const id of section.ruleIds) {
      const rule = ruleById.get(id);
      if (!rule) continue; // enforced plans should never carry unknown ids; defensive only
      lines.push(renderBullet(rule, config));
    }
    lines.push("");
  }

  if (contested.length > 0) {
    lines.push(`## ${CONTESTED_HEADER}`);
    for (const item of contested) {
      lines.push(`- ${sanitize(item.statement)} — ${sanitize(item.reason)}`);
    }
  }

  // Normalize EOF to exactly one trailing newline, regardless of how the last
  // section/contested-block left the lines array.
  return lines.join("\n").replace(/\n+$/, "") + "\n";
}
